sugar_1bul = float(1.5 / 48)
butter_1bul = float(1 / 48)
flour_1bul = float(2.75/48)
client_bul = int(input('Введите количество булок для приготовления: '))
sugar_client = format(sugar_1bul * client_bul, '.2f')
butter_client = format(butter_1bul * client_bul, '.2f')
flour_client = format(flour_1bul * client_bul, '.2f')
print('Для приготовления: ', client_bul, 'булок', 'вам понадобятся: ')
print('Стаканов сахара: ', sugar_client)
print('стаканов масла: ', butter_client)
print('стаканов муки: ', flour_client )
