name = input('Введите ваше имя: ')
city = input('Введите город в котором вы проживаете: ')
republic = input('Введите область проживания: ')
index = input('Введите индекс: ')
phone_number = input('Введите ваш номер телефона: ')
job_special = input('Введите вашу специальность: ')
print('Ваше имя:',  name)
print('Адрес вашего проживания:', city, republic, index)
print('Ваш номер телефона: ', phone_number)
print('Вы работаете:  ', job_special)
